import { useCallback, useRef } from "react";
import { useNavigate, useParams } from "react-router-dom";
import api from "../api/client.js";
import useApiResource from "../hooks/useApiResource.js";
import Spinner from "../components/Spinner.jsx";
import ErrorState from "../components/ErrorState.jsx";
import ReportSection from "../components/report/ReportSection.jsx";
import StatCard from "../components/report/StatCard.jsx";
import TopicBar from "../components/report/TopicBar.jsx";
import PracticeProblemList from "../components/report/PracticeProblemList.jsx";

const STATUS_BADGE = {
    solved: "bg-green-100 text-green-700",
    failed: "bg-red-100 text-red-700",
    unattempted: "bg-gray-100 text-gray-600",
    upsolved: "bg-purple-100 text-purple-700",
};

const STATUS_LABEL = {
    solved: "Solved",
    failed: "Attempted, not solved",
    unattempted: "Never opened",
    upsolved: "Upsolved after the contest",
};

const VERDICT_BADGE = {
    strong: "bg-green-100 text-green-700",
    developing: "bg-amber-100 text-amber-700",
    weak: "bg-red-100 text-red-700",
};

export default function ContestReportPage() {
    const { contestId } = useParams();
    const navigate = useNavigate();

    // Set just before a reload so the next fetch rebuilds the report from
    // scratch instead of returning the stored one.
    const regenerateRef = useRef(false);

    const fetchReport = useCallback(async () => {
        const regenerate = regenerateRef.current;
        regenerateRef.current = false;

        if (!regenerate) {
            try {
                const { data } = await api.get(`/contest/${contestId}/report`);
                return data.report;
            } catch (error) {
                // 404 simply means "not generated yet" - fall through to POST.
                if (error.response?.status !== 404) throw error;
            }
        }

        const { data } = await api.post(
            `/contest/${contestId}/report`,
            {},
            { params: regenerate ? { refresh: "true" } : undefined }
        );

        return data.report;
    }, [contestId]);

    const { data: report, loading, refreshing, error, reload } = useApiResource(fetchReport, {
        fallbackError: "Could not load the performance report.",
    });

    const regenerate = useCallback(() => {
        regenerateRef.current = true;
        reload();
    }, [reload]);

    const retry = useCallback(() => reload(), [reload]);

    if (loading) return <Spinner label="Analysing your contest..." />;

    if (error && !report) {
        return (
            <div className="min-h-screen bg-gray-100 px-4 py-16">
                <ErrorState
                    title="Report unavailable"
                    message={error}
                    onRetry={retry}
                    action={
                        <button
                            onClick={() => navigate("/reports")}
                            className="rounded-xl border border-gray-300 bg-white px-5 py-3 font-semibold text-gray-700 hover:bg-gray-50"
                        >
                            Back to reports
                        </button>
                    }
                />
            </div>
        );
    }

    // Reports generated by version 1 of the app do not carry the topic data.
    if (report && report.version !== 2) {
        return (
            <div className="min-h-screen bg-gray-100 px-4 py-16">
                <ErrorState
                    title="This report predates topic analysis"
                    message="Regenerate it to get the topic breakdown, verdict analysis and practice recommendations."
                    onRetry={regenerate}
                />
            </div>
        );
    }

    const stats = report.stats ?? {};
    const timing = report.timeManagement ?? {};
    const ceiling = report.difficultyCeiling ?? {};

    return (
        <div className="min-h-screen bg-gray-100 px-4 py-10">
            <div className="mx-auto max-w-5xl">
                {/* ------------------------------------------------------ header */}
                <div className="mb-8 flex flex-wrap items-start justify-between gap-4">
                    <div>
                        <h1 className="text-4xl font-bold text-gray-900">Contest #{contestId} report</h1>
                        <p className="mt-2 text-lg text-gray-500">{report.headline}</p>
                        <p className="mt-1 text-sm text-gray-400">
                            {report.generatedBy === "gemini" ? "AI analysis" : "Offline analysis"} ·{" "}
                            {new Date(report.generatedAt).toLocaleString()}
                            {report.user?.handle ? ` · ${report.user.handle}` : ""}
                        </p>
                    </div>

                    <div className="flex gap-3">
                        <button
                            onClick={regenerate}
                            disabled={refreshing || loading}
                            className="rounded-xl border border-gray-300 bg-white px-5 py-3 font-semibold text-gray-700 transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-60"
                        >
                            {refreshing || loading ? "Regenerating..." : "↻ Regenerate"}
                        </button>

                        <button
                            onClick={() => navigate("/reports")}
                            className="rounded-xl border border-gray-300 bg-white px-5 py-3 font-semibold text-gray-700 transition hover:bg-gray-50"
                        >
                            ← Reports
                        </button>
                    </div>
                </div>

                {report.aiError && (
                    <div className="mb-6 rounded-2xl bg-amber-50 p-4 text-amber-800">
                        The AI narrative was unavailable ({report.aiError}), so this report was written by the built-in
                        offline analyser. Every statistic below is still measured from your real submissions.
                    </div>
                )}

                {error && <div className="mb-6 rounded-2xl bg-red-50 p-4 text-red-700">{error}</div>}

                {/* ------------------------------------------------- score + stats */}
                <ReportSection title="Overall score">
                    <div className="flex flex-wrap items-center gap-6">
                        <div className="text-6xl font-bold text-blue-600">{report.overallScore}/10</div>

                        <div className="min-w-48 flex-1">
                            <div className="h-4 overflow-hidden rounded-full bg-gray-200">
                                <div
                                    className="h-full rounded-full bg-blue-600 transition-all"
                                    style={{ width: `${report.overallScore * 10}%` }}
                                />
                            </div>
                            <p className="mt-2 text-sm text-gray-500">
                                Computed from completion, accuracy, engagement and how far above your rating you solved.
                            </p>
                        </div>
                    </div>

                    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                        <StatCard
                            label="Problems solved"
                            value={`${stats.solved}/${stats.totalProblems}`}
                            hint={`${stats.completionRate}% completion`}
                            tone="green"
                        />
                        <StatCard
                            label="Problem accuracy"
                            value={`${stats.problemAccuracy}%`}
                            hint={`${stats.solved} of ${stats.attempted} opened problems`}
                        />
                        <StatCard
                            label="Submission accuracy"
                            value={`${stats.submissionAccuracy}%`}
                            hint={`${stats.totalSubmissions} submissions in the window`}
                            tone="amber"
                        />
                        <StatCard
                            label="Never opened"
                            value={stats.untouched}
                            hint="Problems with no submission"
                            tone={stats.untouched > 0 ? "red" : "gray"}
                        />
                    </div>
                </ReportSection>

                <ReportSection title="Summary">
                    <p className="leading-8 text-gray-700">{report.summary}</p>
                </ReportSection>

                {/* ------------------------------------------ strengths / weaknesses */}
                <div className="mb-6 grid gap-6 md:grid-cols-2">
                    <section className="rounded-3xl bg-white p-8 shadow-sm">
                        <h2 className="mb-4 text-2xl font-bold text-green-600">Strengths</h2>
                        <ul className="space-y-3 text-gray-700">
                            {report.strengths.map((item, index) => (
                                <li key={index} className="flex gap-2">
                                    <span aria-hidden="true">✅</span>
                                    <span>{item}</span>
                                </li>
                            ))}
                        </ul>
                    </section>

                    <section className="rounded-3xl bg-white p-8 shadow-sm">
                        <h2 className="mb-4 text-2xl font-bold text-red-600">Weaknesses</h2>
                        <ul className="space-y-3 text-gray-700">
                            {report.weaknesses.map((item, index) => (
                                <li key={index} className="flex gap-2">
                                    <span aria-hidden="true">❌</span>
                                    <span>{item}</span>
                                </li>
                            ))}
                        </ul>
                    </section>
                </div>

                {/* ------------------------------------------------ topic breakdown */}
                <ReportSection
                    title="Topic performance"
                    subtitle="Every tag that appeared in this contest, ranked by how much practice it needs."
                >
                    {report.topicBreakdown.length === 0 ? (
                        <p className="text-gray-500">No tag information was stored for this contest.</p>
                    ) : (
                        <div className="overflow-x-auto">
                            <table className="w-full min-w-[720px] text-left">
                                <thead>
                                    <tr className="border-b border-gray-200 text-sm text-gray-500">
                                        <th className="pb-3 pr-4 font-medium">Topic</th>
                                        <th className="pb-3 pr-4 font-medium">Solve rate</th>
                                        <th className="pb-3 pr-4 font-medium">Failed</th>
                                        <th className="pb-3 pr-4 font-medium">Never opened</th>
                                        <th className="pb-3 pr-4 font-medium">Avg rating</th>
                                        <th className="pb-3 font-medium">Verdict</th>
                                    </tr>
                                </thead>

                                <tbody className="divide-y divide-gray-100">
                                    {report.topicBreakdown.map((topic) => {
                                        const verdict =
                                            report.topicAnalysis?.find((entry) => entry.tag === topic.tag)?.verdict ??
                                            (topic.solveRate === 100 ? "strong" : topic.solveRate >= 50 ? "developing" : "weak");

                                        return (
                                            <tr key={topic.tag} className="align-top">
                                                <td className="py-4 pr-4">
                                                    <span className="font-semibold text-gray-900">{topic.label}</span>
                                                    <p className="mt-1 max-w-md text-sm text-gray-500">
                                                        {report.topicAnalysis?.find((entry) => entry.tag === topic.tag)?.comment}
                                                    </p>
                                                </td>
                                                <td className="py-4 pr-4">
                                                    <TopicBar solved={topic.solved} total={topic.total} />
                                                </td>
                                                <td className="py-4 pr-4 text-gray-700">{topic.failed}</td>
                                                <td className="py-4 pr-4 text-gray-700">{topic.untouched}</td>
                                                <td className="py-4 pr-4 text-gray-700">{topic.averageRating ?? "—"}</td>
                                                <td className="py-4">
                                                    <span
                                                        className={`rounded-full px-3 py-1 text-xs font-semibold capitalize ${VERDICT_BADGE[verdict]}`}
                                                    >
                                                        {verdict}
                                                    </span>
                                                </td>
                                            </tr>
                                        );
                                    })}
                                </tbody>
                            </table>
                        </div>
                    )}
                </ReportSection>

                {/* ------------------------------- weak topics + practice ladders */}
                <ReportSection
                    title="Topics you did not solve — and what to practise"
                    subtitle="Each topic below cost you at least one problem. The suggested problems are unsolved on your account and sit at the right rating to close the gap."
                    className="ring-2 ring-blue-100"
                >
                    {(!report.weakTopicPlan || report.weakTopicPlan.length === 0) && (
                        <p className="rounded-2xl bg-green-50 p-5 text-green-800">
                            You solved at least one problem in every topic this contest touched. Raise the difficulty next
                            time to find the next gap.
                        </p>
                    )}

                    <div className="space-y-6">
                        {report.weakTopicPlan?.map((topic) => (
                            <article key={topic.tag} className="rounded-2xl border border-gray-200 p-6">
                                <header className="flex flex-wrap items-center justify-between gap-3">
                                    <h3 className="text-xl font-bold text-gray-900">{topic.label}</h3>

                                    <span className="rounded-full bg-red-100 px-3 py-1 text-sm font-semibold text-red-700">
                                        {topic.stats.solved}/{topic.stats.total} solved · {topic.stats.solveRate}%
                                    </span>
                                </header>

                                <p className="mt-3 text-gray-700">{topic.diagnosis}</p>
                                <p className="mt-2 text-sm text-gray-500">{topic.why}</p>

                                {topic.missedInContest?.length > 0 && (
                                    <div className="mt-5">
                                        <h4 className="text-sm font-semibold uppercase tracking-wide text-gray-500">
                                            Missed in this contest
                                        </h4>
                                        <ul className="mt-2 flex flex-wrap gap-2">
                                            {topic.missedInContest.map((problem) => (
                                                <li key={problem.url}>
                                                    <a
                                                        href={problem.url}
                                                        target="_blank"
                                                        rel="noreferrer"
                                                        className="inline-block rounded-full bg-gray-100 px-3 py-1 text-sm text-gray-700 hover:bg-gray-200"
                                                    >
                                                        {problem.index}. {problem.name}
                                                        {problem.rating ? ` (${problem.rating})` : ""}
                                                    </a>
                                                </li>
                                            ))}
                                        </ul>
                                    </div>
                                )}

                                {topic.whatToLearn?.length > 0 && (
                                    <div className="mt-5">
                                        <h4 className="text-sm font-semibold uppercase tracking-wide text-gray-500">
                                            What to learn
                                        </h4>
                                        <ul className="mt-2 list-disc space-y-1 pl-5 text-gray-700">
                                            {topic.whatToLearn.map((item, index) => (
                                                <li key={index}>{item}</li>
                                            ))}
                                        </ul>
                                    </div>
                                )}

                                <div className="mt-5">
                                    <h4 className="text-sm font-semibold uppercase tracking-wide text-gray-500">
                                        Practice ladder
                                    </h4>
                                    <p className="mt-1 mb-3 text-sm text-gray-500">{topic.practiceAdvice}</p>
                                    <PracticeProblemList problems={topic.practiceProblems} />
                                </div>

                                <div className="mt-5 flex flex-wrap gap-3 text-sm">
                                    {topic.resources?.map((resource) => (
                                        <a
                                            key={resource.url}
                                            href={resource.url}
                                            target="_blank"
                                            rel="noreferrer"
                                            className="rounded-full bg-blue-50 px-4 py-2 font-medium text-blue-700 hover:bg-blue-100"
                                        >
                                            📚 {resource.title}
                                        </a>
                                    ))}

                                    <a
                                        href={topic.problemsetUrl}
                                        target="_blank"
                                        rel="noreferrer"
                                        className="rounded-full bg-blue-50 px-4 py-2 font-medium text-blue-700 hover:bg-blue-100"
                                    >
                                        🔎 All {topic.label} problems
                                    </a>
                                </div>
                            </article>
                        ))}
                    </div>
                </ReportSection>

                {/* --------------------------------------------- difficulty ceiling */}
                <ReportSection title="Difficulty analysis">
                    <p className="leading-8 text-gray-700">{report.difficultyAnalysis}</p>

                    <div className="mt-6 grid gap-4 sm:grid-cols-3">
                        <StatCard label="Your rating" value={ceiling.userRating ?? "unrated"} tone="gray" />
                        <StatCard
                            label="Highest solved"
                            value={ceiling.highestSolvedRating ?? "—"}
                            tone={ceiling.brokeCeiling ? "green" : "gray"}
                            hint={ceiling.brokeCeiling ? "Above your current rating" : undefined}
                        />
                        <StatCard label="Lowest unsolved" value={ceiling.lowestUnsolvedRating ?? "—"} tone="red" />
                    </div>

                    {report.ratingBreakdown?.length > 0 && (
                        <div className="mt-8 space-y-3">
                            <h3 className="text-sm font-semibold uppercase tracking-wide text-gray-500">
                                By rating band
                            </h3>
                            {report.ratingBreakdown.map((band) => (
                                <div key={band.band} className="flex flex-wrap items-center gap-4">
                                    <span className="w-28 shrink-0 font-medium text-gray-700">{band.band}</span>
                                    <TopicBar solved={band.solved} total={band.total} />
                                </div>
                            ))}
                        </div>
                    )}
                </ReportSection>

                {/* ------------------------------------------------------- verdicts */}
                <ReportSection title="Submission verdicts" subtitle="What your failed submissions say about the failure mode.">
                    <p className="leading-8 text-gray-700">{report.verdictAnalysis}</p>

                    {report.verdictBreakdown?.length > 0 && (
                        <ul className="mt-6 space-y-3">
                            {report.verdictBreakdown.map((entry) => (
                                <li key={entry.verdict} className="rounded-2xl border border-gray-200 p-4">
                                    <div className="flex flex-wrap items-center justify-between gap-3">
                                        <span className="font-semibold text-gray-900">{entry.label}</span>
                                        <span className="text-sm text-gray-600">
                                            {entry.count} submission{entry.count === 1 ? "" : "s"} · {entry.share}%
                                        </span>
                                    </div>
                                    {entry.diagnosis && <p className="mt-2 text-sm text-gray-600">{entry.diagnosis}</p>}
                                </li>
                            ))}
                        </ul>
                    )}
                </ReportSection>

                {/* ------------------------------------------------ time management */}
                <ReportSection title="Time management">
                    <p className="leading-8 text-gray-700">{report.timeManagementAnalysis}</p>

                    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                        <StatCard label="Contest length" value={`${timing.durationMinutes} min`} tone="gray" />
                        <StatCard label="First solve" value={timing.firstSolveMinute !== null ? `${timing.firstSolveMinute} min` : "—"} />
                        <StatCard label="Last solve" value={timing.lastSolveMinute !== null ? `${timing.lastSolveMinute} min` : "—"} />
                        <StatCard
                            label="Unused time"
                            value={`${timing.unusedMinutes} min`}
                            tone={timing.unusedMinutes > timing.durationMinutes * 0.3 ? "red" : "green"}
                        />
                    </div>

                    {timing.solveTimeline?.length > 0 && (
                        <ol className="mt-8 space-y-2 border-l-2 border-blue-200 pl-6">
                            {timing.solveTimeline.map((entry) => (
                                <li key={`${entry.index}-${entry.minute}`} className="relative">
                                    <span className="absolute -left-[1.9rem] top-1.5 h-3 w-3 rounded-full bg-blue-500" />
                                    <span className="font-medium text-gray-900">
                                        Minute {entry.minute} — {entry.index}. {entry.name}
                                    </span>
                                    {entry.rating && <span className="ml-2 text-sm text-gray-500">({entry.rating})</span>}
                                </li>
                            ))}
                        </ol>
                    )}
                </ReportSection>

                {/* ------------------------------------------------ problem analysis */}
                <ReportSection title="Problem-by-problem analysis">
                    <div className="space-y-4">
                        {report.problems.map((problem) => {
                            const comment = report.problemAnalysis?.find(
                                (entry) => entry.index === problem.index && entry.name === problem.name
                            )?.comment;

                            return (
                                <article key={problem.key} className="rounded-2xl border border-gray-200 p-5">
                                    <header className="flex flex-wrap items-center justify-between gap-3">
                                        <h3 className="text-lg font-bold text-gray-900">
                                            <a href={problem.url} target="_blank" rel="noreferrer" className="hover:underline">
                                                {problem.index}. {problem.name}
                                            </a>
                                        </h3>

                                        <div className="flex flex-wrap items-center gap-2">
                                            <span className={`rounded-full px-3 py-1 text-xs font-semibold ${STATUS_BADGE[problem.status]}`}>
                                                {STATUS_LABEL[problem.status]}
                                            </span>
                                            {problem.rating && (
                                                <span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-700">
                                                    {problem.rating}
                                                </span>
                                            )}
                                        </div>
                                    </header>

                                    {problem.tags?.length > 0 && (
                                        <p className="mt-2 flex flex-wrap gap-2">
                                            {problem.tags.map((tag) => (
                                                <span key={tag} className="rounded-full bg-gray-100 px-2.5 py-0.5 text-xs text-gray-600">
                                                    {tag}
                                                </span>
                                            ))}
                                        </p>
                                    )}

                                    <p className="mt-3 text-gray-600">{comment}</p>

                                    <dl className="mt-4 flex flex-wrap gap-x-8 gap-y-2 text-sm text-gray-500">
                                        <div className="flex gap-1">
                                            <dt>Submissions:</dt>
                                            <dd className="font-medium text-gray-700">{problem.attempts}</dd>
                                        </div>
                                        <div className="flex gap-1">
                                            <dt>Wrong attempts:</dt>
                                            <dd className="font-medium text-gray-700">{problem.wrongAttempts}</dd>
                                        </div>
                                        {problem.solvedAtMinute !== null && (
                                            <div className="flex gap-1">
                                                <dt>Solved at:</dt>
                                                <dd className="font-medium text-gray-700">minute {problem.solvedAtMinute}</dd>
                                            </div>
                                        )}
                                        {problem.verdicts?.length > 0 && (
                                            <div className="flex gap-1">
                                                <dt>Verdicts:</dt>
                                                <dd className="font-medium text-gray-700">{problem.verdicts.join(", ")}</dd>
                                            </div>
                                        )}
                                    </dl>
                                </article>
                            );
                        })}
                    </div>
                </ReportSection>

                {/* ----------------------------------------- recommendations + goals */}
                <div className="mb-6 grid gap-6 md:grid-cols-2">
                    <section className="rounded-3xl bg-white p-8 shadow-sm">
                        <h2 className="mb-4 text-2xl font-bold text-gray-900">Recommendations</h2>
                        <ol className="list-decimal space-y-3 pl-6 text-gray-700">
                            {report.recommendations.map((item, index) => (
                                <li key={index}>{item}</li>
                            ))}
                        </ol>
                    </section>

                    <section className="rounded-3xl bg-white p-8 shadow-sm">
                        <h2 className="mb-4 text-2xl font-bold text-gray-900">Goals for the next contest</h2>
                        <ul className="space-y-3 text-gray-700">
                            {report.nextContestGoals?.map((item, index) => (
                                <li key={index} className="flex gap-2">
                                    <span aria-hidden="true">🎯</span>
                                    <span>{item}</span>
                                </li>
                            ))}
                        </ul>
                    </section>
                </div>

                {/* ----------------------------------------------------- motivation */}
                <section className="rounded-3xl bg-linear-to-r from-blue-600 to-indigo-600 p-8 text-white shadow-sm">
                    <h2 className="mb-4 text-2xl font-bold">Keep going</h2>
                    <p className="leading-8">{report.motivation}</p>
                </section>
            </div>
        </div>
    );
}
